import type { AdminUser, AdminQuestion, AdminAnnouncement, SimulationStat } from './types';

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 'u-101',
    name: 'Alex Rivera',
    email: 'alex.rivera@university.edu',
    role: 'student',
    status: 'active',
    progress: 85,
    quizzesCompleted: 6,
    experimentsCount: 14,
    lastActive: '10 mins ago',
    createdAt: '2026-08-15',
  },
  {
    id: 'u-102',
    name: 'Dr. Sarah Connor',
    email: 'sarah.connor@oslab.edu',
    role: 'instructor',
    status: 'active',
    progress: 100,
    quizzesCompleted: 8,
    experimentsCount: 32,
    lastActive: 'Just now',
    createdAt: '2026-07-01',
  },
  {
    id: 'u-103',
    name: 'Rohan Sharma',
    email: 'rohan.s@student.edu',
    role: 'student',
    status: 'active',
    progress: 60,
    quizzesCompleted: 4,
    experimentsCount: 9,
    lastActive: '2 hours ago',
    createdAt: '2026-09-01',
  },
  {
    id: 'u-104',
    name: 'Elena Rostova',
    email: 'elena.r@student.edu',
    role: 'student',
    status: 'suspended',
    progress: 25,
    quizzesCompleted: 2,
    experimentsCount: 3,
    lastActive: '3 days ago',
    createdAt: '2026-09-10',
  },
  {
    id: 'u-105',
    name: 'System Admin',
    email: 'admin@oslab.edu',
    role: 'admin',
    status: 'active',
    progress: 100,
    quizzesCompleted: 8,
    experimentsCount: 50,
    lastActive: 'Active now',
    createdAt: '2026-06-01',
  },
];

export const INITIAL_QUESTIONS: AdminQuestion[] = [
  {
    id: 'q-1',
    topicSlug: 'processes-and-threads',
    topicName: 'Processes & Threads',
    question: 'Which of the following is NOT shared between threads of the same process?',
    options: ['Code section', 'Stack memory', 'Data section', 'Open file descriptors'],
    correctAnswer: 1,
    explanation: 'Each thread has its own private execution stack and registers, while sharing code, data, and heap.',
    difficulty: 'medium',
    successRate: 74,
  },
  {
    id: 'q-2',
    topicSlug: 'cpu-scheduling',
    topicName: 'CPU Scheduling',
    question: 'Which CPU scheduling algorithm can lead to the "convoy effect"?',
    options: ['Round Robin', 'Shortest Job First', 'First-Come First-Served (FCFS)', 'Multilevel Feedback Queue'],
    correctAnswer: 2,
    explanation: 'In FCFS, short processes can get stuck waiting behind long CPU-burst processes (the convoy effect).',
    difficulty: 'easy',
    successRate: 91,
  },
  {
    id: 'q-3',
    topicSlug: 'memory-management',
    topicName: 'Memory Management',
    question: 'Belady\'s Anomaly occurs in which page replacement algorithm?',
    options: ['LRU (Least Recently Used)', 'FIFO (First-In First-Out)', 'Optimal Page Replacement', 'Clock Algorithm'],
    correctAnswer: 1,
    explanation: 'FIFO can suffer from Belady\'s Anomaly where increasing the number of page frames results in more page faults.',
    difficulty: 'hard',
    successRate: 58,
  },
  {
    id: 'q-4',
    topicSlug: 'disk-scheduling',
    topicName: 'Disk Scheduling',
    question: 'In SCAN (Elevator) disk scheduling, what happens when the head reaches the end of the disk?',
    options: ['Jumps to cylinder 0 immediately', 'Reverses direction and serves requests on return', 'Stops until new requests arrive', 'Clears the queue'],
    correctAnswer: 1,
    explanation: 'SCAN moves in one direction servicing requests until it hits the end, then reverses direction.',
    difficulty: 'easy',
    successRate: 88,
  },
  {
    id: 'q-5',
    topicSlug: 'deadlocks-and-synchronization',
    topicName: 'Deadlocks & Synchronization',
    question: 'What is the necessary condition for deadlock that Banker\'s Algorithm avoids?',
    options: ['Mutual Exclusion', 'Circular Wait', 'No Preemption', 'Hold and Wait'],
    correctAnswer: 1,
    explanation: 'Banker\'s algorithm tests for safe states to ensure circular wait conditions never manifest.',
    difficulty: 'hard',
    successRate: 62,
  },
];

export const INITIAL_ANNOUNCEMENTS: AdminAnnouncement[] = [
  {
    id: 'ann-1',
    title: 'Lab 2: CPU Scheduling Submission Due',
    message: 'All students must submit their Round Robin and SJF simulation analysis by Friday 11:59 PM.',
    type: 'urgent',
    createdAt: '2026-09-24',
    active: true,
    target: 'students',
  },
  {
    id: 'ann-2',
    title: 'Mini-OS System Kernel v2.4 Released',
    message: 'New simulated commands (kill, ps, cat, top) are now enabled in the Mini-OS virtual terminal.',
    type: 'success',
    createdAt: '2026-09-22',
    active: true,
    target: 'all',
  },
  {
    id: 'ann-3',
    title: 'Scheduled Server Maintenance',
    message: 'OSLab backend services will undergo a brief 10-minute maintenance window this Sunday at 02:00 AM UTC.',
    type: 'info',
    createdAt: '2026-09-20',
    active: false,
    target: 'all',
  },
];

export const SIMULATION_STATS: SimulationStat[] = [
  { algorithm: 'Round Robin (RR)', type: 'CPU', runsCount: 428, avgTurnaround: 14.2 },
  { algorithm: 'Shortest Job First (SJF)', type: 'CPU', runsCount: 312, avgTurnaround: 11.5 },
  { algorithm: 'First-Come First-Served (FCFS)', type: 'CPU', runsCount: 289, avgTurnaround: 18.6 },
  { algorithm: 'Priority Scheduling', type: 'CPU', runsCount: 194, avgTurnaround: 13.8 },
  { algorithm: 'LRU Page Replacement', type: 'Memory', runsCount: 245, avgPageFaults: 6.4 },
  { algorithm: 'FIFO Page Replacement', type: 'Memory', runsCount: 210, avgPageFaults: 8.2 },
  { algorithm: 'C-SCAN Disk Scheduling', type: 'Disk', runsCount: 188, avgHeadMovement: 320 },
  { algorithm: 'SSTF Disk Scheduling', type: 'Disk', runsCount: 165, avgHeadMovement: 240 },
];
