import { Question } from './quiz.model';
import { IQuestionInput } from './quiz.types';

export const seedQuestions: IQuestionInput[] = [
  // =========================================================================
  // MODULE 1: FOUNDATIONS & KERNEL ARCHITECTURE (5 Questions)
  // =========================================================================
  {
    stableId: 'foundations-q001',
    topic: 'foundations',
    question: 'What is the primary role of an Operating System (OS)?',
    options: [
      'To compile source code into machine executables',
      'To act as an intermediary between computer hardware and applications, managing resources',
      'To serve solely as a permanent database management system',
      'To power on the physical power supply unit (PSU)',
    ],
    correctAnswer: 1,
    explanation: 'The OS abstracts physical hardware, manages CPU, memory, and I/O devices, and provides standard APIs for user applications.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'intro-to-os',
  },
  {
    stableId: 'foundations-q002',
    topic: 'foundations',
    question: 'Why does modern CPU architecture enforce dual-mode operation (User Mode vs Kernel Mode)?',
    options: [
      'To allow user apps to run twice as fast',
      'To prevent user applications from directly executing privileged instructions that could crash the system',
      'To enable multi-monitor display outputs',
      'To double the physical clock speed of the processor',
    ],
    correctAnswer: 1,
    explanation: 'Dual-mode execution isolates user applications in Ring 3 (User mode) and kernel code in Ring 0 (Kernel mode), protecting critical hardware and memory structures.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'user-vs-kernel-mode',
  },
  {
    stableId: 'foundations-q003',
    topic: 'foundations',
    question: 'How does an application in User Mode safely request a privileged service (such as writing to a disk file) from the OS kernel?',
    options: [
      'By directly modifying the CPU instruction pointer to ring 0 memory',
      'By invoking a System Call (syscall / software trap) into kernel mode',
      'By bypassing the kernel and directly writing to the disk controller registers',
      'By restarting the computer into single-user mode',
    ],
    correctAnswer: 1,
    explanation: 'System calls trigger a software interrupt (trap) that safely switches the CPU from User Mode to Kernel Mode via the system call dispatch table.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'system-calls',
  },
  {
    stableId: 'foundations-q004',
    topic: 'foundations',
    question: 'What hardware mechanism allows I/O devices (like network cards and disks) to transfer data directly to RAM without continuous CPU intervention?',
    options: [
      'Programmed I/O (PIO)',
      'Direct Memory Access (DMA)',
      'Instruction Pipelining',
      'Branch Prediction',
    ],
    correctAnswer: 1,
    explanation: 'DMA controllers transfer large blocks of data directly between I/O devices and RAM, freeing the CPU to execute other compute tasks.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'hardware-architecture',
  },
  {
    stableId: 'foundations-q005',
    topic: 'foundations',
    question: 'What sequence occurs during a system boot from a cold power-on state?',
    options: [
      'Firmware (BIOS/UEFI) POST -> Bootloader -> OS Kernel Initialization -> Init/Systemd User space',
      'OS Kernel -> BIOS/UEFI -> Web Browser -> Application launcher',
      'User Apps -> Shell -> Bootloader -> Hardware POST',
      'Direct memory write from SSD to CPU registers without firmware',
    ],
    correctAnswer: 0,
    explanation: 'BIOS/UEFI performs the Power-On Self-Test (POST), loads the Master Boot Record / EFI bootloader, which in turn loads the OS kernel into memory to initialize subsystem drivers.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'intro-to-os',
  },

  // =========================================================================
  // MODULE 2: PROCESSES, THREADS & CPU SCHEDULING (5 Questions + Calculations)
  // =========================================================================
  {
    stableId: 'processes-cpu-q001',
    topic: 'processes-cpu',
    question: 'Which kernel data structure stores critical metadata for managing an individual process (PID, CPU registers, Program Counter, State)?',
    options: [
      'Task Memory Descriptor (TMD)',
      'Process Control Block (PCB)',
      'Segment Descriptor Array',
      'Interrupt Vector Table',
    ],
    correctAnswer: 1,
    explanation: 'The PCB (Process Control Block) holds all contextual runtime state for a process required during context switching.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'processes',
    labSimulatorLink: '/mini-os',
  },
  {
    stableId: 'processes-cpu-q002',
    topic: 'processes-cpu',
    question: 'Three processes arrive at time t = 0 with burst times: P1 = 6 ms, P2 = 4 ms, P3 = 2 ms. Using Non-Preemptive Shortest Job First (SJF), what is the Average Waiting Time (AWT)?',
    options: [
      '2.0 ms',
      '2.67 ms',
      '3.0 ms',
      '4.0 ms',
    ],
    correctAnswer: 1,
    explanation: 'Execution order: P3 (burst 2, wait = 0), then P2 (burst 4, wait = 2), then P1 (burst 6, wait = 6). Total waiting time = 0 + 2 + 6 = 8 ms. Average Waiting Time = 8 / 3 ≈ 2.67 ms.',
    difficulty: 'hard',
    marks: 2,
    reviewTopicSlug: 'cpu-scheduling',
    labSimulatorLink: '/os-lab/cpu-scheduling',
  },
  {
    stableId: 'processes-cpu-q003',
    topic: 'processes-cpu',
    question: 'What is the "Convoy Effect" commonly observed in First-Come, First-Served (FCFS) CPU scheduling?',
    options: [
      'Short processes get delayed behind a CPU-intensive long process, drastically increasing average waiting time',
      'Multiple CPUs attempting to write to the same cache line',
      'Processes deadlocking due to circular wait',
      'Processes continually preempting one another in Round Robin',
    ],
    correctAnswer: 0,
    explanation: 'In FCFS, when a long CPU-bound job runs first, all short I/O-bound processes wait behind it, causing poor CPU and device utilization.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'cpu-scheduling',
    labSimulatorLink: '/os-lab/cpu-scheduling',
  },
  {
    stableId: 'processes-cpu-q004',
    topic: 'processes-cpu',
    question: 'In Round Robin scheduling with 3 processes (P1=8 ms, P2=4 ms, P3=2 ms, all arriving at t=0) and Time Quantum q = 3 ms, at what time t does P2 finish execution?',
    options: [
      't = 8 ms',
      't = 9 ms',
      't = 12 ms',
      't = 14 ms',
    ],
    correctAnswer: 2,
    explanation: 'Timeline: [0-3]: P1 (rem: 5), [3-6]: P2 (rem: 1), [6-8]: P3 completes (rem: 0), [8-11]: P1 (rem: 2), [11-12]: P2 completes (rem: 0). P2 finishes at t = 12 ms.',
    difficulty: 'hard',
    marks: 2,
    reviewTopicSlug: 'cpu-scheduling',
    labSimulatorLink: '/os-lab/cpu-scheduling',
  },
  {
    stableId: 'processes-cpu-q005',
    topic: 'processes-cpu',
    question: 'How do threads (lightweight processes) differ from standard separate OS processes?',
    options: [
      'Threads have their own independent virtual address space and file descriptor tables',
      'Threads share the same virtual address space, heap, and open files of their parent process, but have independent stacks and registers',
      'Threads cannot be scheduled onto separate CPU cores',
      'Threads do not require context switching',
    ],
    correctAnswer: 1,
    explanation: 'Threads within the same process share code, data, heap, and OS resources, while maintaining private registers, stack pointer, and program counter.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'threads-multithreading',
  },

  // =========================================================================
  // MODULE 3: SYNCHRONIZATION & DEADLOCKS (5 Questions + Calculation)
  // =========================================================================
  {
    stableId: 'synchronization-deadlocks-q001',
    topic: 'synchronization-deadlocks',
    question: 'What is a Race Condition in concurrent programming?',
    options: [
      'A condition where two CPUs compete to execute instructions with the highest clock speed',
      'A situation where multiple concurrent threads access shared data and the final outcome depends on the non-deterministic order of execution',
      'A hardware error when RAM frequency is mismatched with the motherboard',
      'A process exceeding its CPU time quantum',
    ],
    correctAnswer: 1,
    explanation: 'Race conditions occur when shared mutable data is accessed without proper synchronization, causing bugs that depend on thread timing.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'synchronization-race-conditions',
  },
  {
    stableId: 'synchronization-deadlocks-q002',
    topic: 'synchronization-deadlocks',
    question: 'Which of the following is NOT one of the 4 Coffman conditions required for a Deadlock to occur?',
    options: [
      'Mutual Exclusion',
      'Hold and Wait',
      'Preemptive Resource Allocation',
      'Circular Wait',
    ],
    correctAnswer: 2,
    explanation: 'The Coffman condition is "No Preemption" (resources cannot be forcibly confiscated). If preemption is allowed, deadlock is prevented.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'deadlocks',
  },
  {
    stableId: 'synchronization-deadlocks-q003',
    topic: 'synchronization-deadlocks',
    question: 'A counting semaphore S is initialized to 5. After 8 wait() (P) operations and 5 signal() (V) operations, what is the final value of S?',
    options: [
      '0',
      '2',
      '-3',
      '5',
    ],
    correctAnswer: 1,
    explanation: 'Initial S = 5. After 8 wait() operations: 5 - 8 = -3. After 5 signal() operations: -3 + 5 = 2. Final value = 2.',
    difficulty: 'medium',
    marks: 2,
    reviewTopicSlug: 'semaphores-mutexes',
  },
  {
    stableId: 'synchronization-deadlocks-q004',
    topic: 'synchronization-deadlocks',
    question: 'In Banker\'s Algorithm for deadlock avoidance, a system is in a "Safe State" if:',
    options: [
      'No process has requested any resources',
      'There exists at least one safe sequence <P1, P2, ... Pn> where every process can obtain its maximum needed resources and finish',
      'The CPU utilization is at 100%',
      'All semaphores have positive values',
    ],
    correctAnswer: 1,
    explanation: 'A state is safe if the OS can guarantee an execution sequence allowing all processes to complete without deadlock.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'deadlocks',
  },
  {
    stableId: 'synchronization-deadlocks-q005',
    topic: 'synchronization-deadlocks',
    question: 'What is the primary difference between a Mutex and a Binary Semaphore?',
    options: [
      'A Mutex has ownership semantics (only the thread that locked it can unlock it), whereas a semaphore can be signaled by any thread',
      'A Mutex is implemented in hardware while semaphores are pure software',
      'A Mutex can take any integer value up to 100',
      'A Binary Semaphore is only used in single-threaded environments',
    ],
    correctAnswer: 0,
    explanation: 'Mutexes have strict ownership (only the acquiring thread can release it), whereas semaphores are signaling mechanisms that any thread or ISR can trigger.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'semaphores-mutexes',
  },

  // =========================================================================
  // MODULE 4: MEMORY MANAGEMENT & VIRTUAL PAGING (5 Questions + Calculations)
  // =========================================================================
  {
    stableId: 'memory-management-q001',
    topic: 'memory-management',
    question: 'Given an empty memory with 3 page frames, how many Page Faults occur for reference string: [7, 0, 1, 2, 0, 3, 0] using FIFO Page Replacement?',
    options: [
      '4 Page Faults',
      '5 Page Faults',
      '6 Page Faults',
      '7 Page Faults',
    ],
    correctAnswer: 2,
    explanation: '1. Ref 7 -> [7] (Fault 1)\n2. Ref 0 -> [7, 0] (Fault 2)\n3. Ref 1 -> [7, 0, 1] (Fault 3)\n4. Ref 2 -> replaces 7 -> [2, 0, 1] (Fault 4)\n5. Ref 0 -> Hit [2, 0, 1]\n6. Ref 3 -> replaces 0 -> [2, 3, 1] (Fault 5)\n7. Ref 0 -> replaces 1 -> [2, 3, 0] (Fault 6). Total = 6 faults.',
    difficulty: 'hard',
    marks: 2,
    reviewTopicSlug: 'virtual-memory',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'memory-management-q002',
    topic: 'memory-management',
    question: 'What hardware component acts as a high-speed associative cache for the Page Table to speed up virtual-to-physical address translation?',
    options: [
      'Direct Memory Access (DMA)',
      'Translation Lookaside Buffer (TLB)',
      'Memory Controller Hub (Northbridge)',
      'Instruction Decoder',
    ],
    correctAnswer: 1,
    explanation: 'The TLB (Translation Lookaside Buffer) caches recently accessed page table entries in fast on-chip associative memory.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'paging-segmentation',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'memory-management-q003',
    topic: 'memory-management',
    question: 'What is Belady\'s Anomaly in virtual memory?',
    options: [
      'When increasing physical RAM size causes the CPU frequency to drop',
      'The counter-intuitive phenomenon where increasing the number of page frames results in MORE page faults for certain reference strings under FIFO',
      'When the page table size exceeds available RAM',
      'When memory fragmentation reaches 100%',
    ],
    correctAnswer: 1,
    explanation: 'Belady\'s Anomaly occurs in FIFO replacement where adding more page frames can actually increase the number of page faults.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'virtual-memory',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'memory-management-q004',
    topic: 'memory-management',
    question: 'What severe performance issue occurs when a system spends more time swapping pages in and out of disk than executing user instructions?',
    options: [
      'Deadlock',
      'Thrashing',
      'Starvation',
      'Pipeline Stall',
    ],
    correctAnswer: 1,
    explanation: 'Thrashing occurs when the working sets of active processes exceed physical memory, causing continuous page faults and near-zero CPU throughput.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'virtual-memory',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'memory-management-q005',
    topic: 'memory-management',
    question: 'If a virtual address space uses 32-bit addresses and a page size of 4 KB (2^12 bytes), how many entries are in a single-level page table?',
    options: [
      '1,024 (2^10)',
      '65,536 (2^16)',
      '1,048,576 (2^20)',
      '4,294,967,296 (2^32)',
    ],
    correctAnswer: 2,
    explanation: 'Offset requires 12 bits (4 KB = 2^12 bytes). Remaining bits for page number = 32 - 12 = 20 bits. Number of page table entries = 2^20 = 1,048,576.',
    difficulty: 'hard',
    marks: 2,
    reviewTopicSlug: 'paging-segmentation',
    labSimulatorLink: '/os-lab/memory-management',
  },

  // =========================================================================
  // MODULE 5: STORAGE HARDWARE & DISK SCHEDULING (5 Questions + Seek Calc)
  // =========================================================================
  {
    stableId: 'storage-disk-q001',
    topic: 'storage-disk',
    question: 'Disk head is at cylinder 50. Request queue: [82, 170, 43, 140, 24]. Using Shortest Seek Time First (SSTF), which request is serviced FIRST?',
    options: [
      '82',
      '43',
      '24',
      '170',
    ],
    correctAnswer: 1,
    explanation: 'Head is at 50. Distances: |50-82|=32, |50-170|=120, |50-43|=7, |50-140|=90, |50-24|=26. Minimum seek distance is |50-43|=7, so 43 is serviced first.',
    difficulty: 'medium',
    marks: 2,
    reviewTopicSlug: 'disk-management',
    labSimulatorLink: '/os-lab/disk-scheduling',
  },
  {
    stableId: 'storage-disk-q002',
    topic: 'storage-disk',
    question: 'In Unix file systems, what information is stored inside an Inode (Index Node)?',
    options: [
      'File data contents and the file name only',
      'File size, permissions, owner, timestamps, and direct/indirect disk block pointers (excluding the file name)',
      'The CPU process scheduling priority',
      'The bootloader sector code',
    ],
    correctAnswer: 1,
    explanation: 'Inodes store all file metadata and data block pointers. The human-readable filename is stored in directory entry tables that map names to inode numbers.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'file-systems',
  },
  {
    stableId: 'storage-disk-q003',
    topic: 'storage-disk',
    question: 'How does the LOOK disk scheduling algorithm improve upon the SCAN (Elevator) algorithm?',
    options: [
      'LOOK moves randomly across the disk surface',
      'LOOK reverses direction immediately after servicing the last pending request in the current direction, without traveling to the disk boundary (cylinder 0 or max)',
      'LOOK only services write operations',
      'LOOK disables disk caching completely',
    ],
    correctAnswer: 1,
    explanation: 'SCAN travels all the way to cylinder 0 or max boundary before reversing. LOOK checks for pending requests and reverses as soon as none remain ahead.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'disk-management',
    labSimulatorLink: '/os-lab/disk-scheduling',
  },
  {
    stableId: 'storage-disk-q004',
    topic: 'storage-disk',
    question: 'What is the primary advantage of Indexed File Allocation over Contiguous Allocation?',
    options: [
      'Eliminates external fragmentation and supports direct random access without knowing file size in advance',
      'Requires zero index block overhead',
      'Files cannot be deleted',
      'Disk read speed is equal to RAM speed',
    ],
    correctAnswer: 0,
    explanation: 'Indexed allocation uses an index block containing pointers to scattered disk blocks, preventing external fragmentation while maintaining direct random access.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'file-systems',
  },
  {
    stableId: 'storage-disk-q005',
    topic: 'storage-disk',
    question: 'What is disk "Rotational Latency"?',
    options: [
      'The time taken for the read/write head arm to move across tracks',
      'The time required for the target disk sector on the platter to rotate directly beneath the read/write head',
      'The time to transfer data from the disk buffer to main memory',
      'The time the OS spends preparing the I/O request packet',
    ],
    correctAnswer: 1,
    explanation: 'Seek time is arm movement to the cylinder; Rotational latency is waiting for the target sector on the spinning platter to rotate under the head.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'disk-management',
    labSimulatorLink: '/os-lab/disk-scheduling',
  },

  // =========================================================================
  // MODULE 6: SECURITY & VIRTUALIZATION (5 Questions)
  // =========================================================================
  {
    stableId: 'security-virtualization-q001',
    topic: 'security-virtualization',
    question: 'What is the fundamental architectural difference between Type 1 (Bare-Metal) and Type 2 (Hosted) Hypervisors?',
    options: [
      'Type 1 runs directly on host hardware without an underlying OS; Type 2 runs as an application on top of a host OS',
      'Type 1 only supports Windows; Type 2 only supports Linux',
      'Type 1 cannot run virtual machines',
      'Type 2 does not use CPU virtualization extensions',
    ],
    correctAnswer: 0,
    explanation: 'Type 1 (KVM, ESXi, Xen) sits directly on bare-metal hardware for high efficiency. Type 2 (VirtualBox, VMware Workstation) runs as a process inside a host OS.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'virtualization-containers',
  },
  {
    stableId: 'security-virtualization-q002',
    topic: 'security-virtualization',
    question: 'How do OS Containers (like Docker) provide lightweight isolation compared to Virtual Machines?',
    options: [
      'Containers emulate separate physical hardware and run full duplicate guest OS kernels',
      'Containers share the single host OS kernel and use Linux Namespaces (isolation) and cgroups (resource limits)',
      'Containers require dedicated BIOS firmware per container',
      'Containers run exclusively in CPU Ring 0 kernel mode',
    ],
    correctAnswer: 1,
    explanation: 'Containers share the host kernel, utilizing Namespaces for process/network isolation and cgroups for CPU/memory throttling without the overhead of a full guest OS.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'virtualization-containers',
  },
  {
    stableId: 'security-virtualization-q003',
    topic: 'security-virtualization',
    question: 'What is the Principle of Least Privilege in Operating System Security?',
    options: [
      'Granting all users administrative root access by default to avoid permission errors',
      'Every program and user should operate using the minimum set of privileges necessary to perform its specific task',
      'Disabling file passwords across the local network',
      'Restricting CPU clock frequency for background tasks',
    ],
    correctAnswer: 1,
    explanation: 'The Principle of Least Privilege minimizes damage from security compromises or bugs by strictly granting only necessary permissions.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'security-protection',
  },
  {
    stableId: 'security-virtualization-q004',
    topic: 'security-virtualization',
    question: 'Which Linux kernel feature is responsible for isolating process IDs (PID), network interfaces, and filesystem mount points for containers?',
    options: [
      'Control Groups (cgroups)',
      'Linux Namespaces',
      'System Call Table',
      'Direct Memory Access (DMA)',
    ],
    correctAnswer: 1,
    explanation: 'Namespaces provide isolated views of system resources (PID, Mount, Net, IPC, UTS), while cgroups regulate and limit resource consumption.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'virtualization-containers',
  },
  {
    stableId: 'security-virtualization-q005',
    topic: 'security-virtualization',
    question: 'What security mechanism randomizes the memory addresses of key program areas (stack, heap, libraries) to defend against buffer overflow attacks?',
    options: [
      'Access Control Matrix',
      'Address Space Layout Randomization (ASLR)',
      'Direct Page Swapping',
      'Symmetric Multiprocessing (SMP)',
    ],
    correctAnswer: 1,
    explanation: 'ASLR randomizes memory layout offsets during process execution, preventing attackers from predicting jump targets in buffer overflow exploits.',
    difficulty: 'hard',
    marks: 1,
    reviewTopicSlug: 'security-protection',
  },

  // =========================================================================
  // GRAND FINAL CERTIFICATION EXAM (20 Questions - Mixed Comprehensive)
  // =========================================================================
  {
    stableId: 'final-exam-q001',
    topic: 'final-exam',
    question: 'When a CPU switches from executing Process A to Process B, saving state A and loading state B into registers is known as:',
    options: ['Interrupt Vectoring', 'Context Switching', 'Page Replacement', 'Process Thrashing'],
    correctAnswer: 1,
    explanation: 'Context switching is the kernel procedure of saving the state of the active process in its PCB and restoring the state of the newly scheduled process.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'processes',
    labSimulatorLink: '/mini-os',
  },
  {
    stableId: 'final-exam-q002',
    topic: 'final-exam',
    question: 'Processes P1 (burst 8 ms), P2 (burst 4 ms), P3 (burst 1 ms) arrive at t=0. Under Shortest Job First (SJF), what is the waiting time of Process P1?',
    options: ['0 ms', '1 ms', '5 ms', '13 ms'],
    correctAnswer: 2,
    explanation: 'Execution order: P3 (runs 0-1 ms, wait = 0), then P2 (runs 1-5 ms, wait = 1), then P1 (runs 5-13 ms, wait = 5 ms). P1 waiting time = 5 ms.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'cpu-scheduling',
    labSimulatorLink: '/os-lab/cpu-scheduling',
  },
  {
    stableId: 'final-exam-q003',
    topic: 'final-exam',
    question: 'What happens when the time quantum in Round Robin CPU scheduling is set excessively small (e.g., 0.1 ms)?',
    options: [
      'System throughput reaches maximum possible performance',
      'Context switching overhead dominates CPU time, degrading overall system throughput',
      'The scheduling degenerates into First-Come, First-Served (FCFS)',
      'Starvation of short processes occurs',
    ],
    correctAnswer: 1,
    explanation: 'If the quantum is too small, the CPU spends most of its cycles performing context switches rather than executing user code.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'cpu-scheduling',
    labSimulatorLink: '/os-lab/cpu-scheduling',
  },
  {
    stableId: 'final-exam-q004',
    topic: 'final-exam',
    question: 'Which technique permanently solves the Starvation problem in Priority Scheduling by gradually increasing the priority of waiting processes over time?',
    options: ['Compaction', 'Aging', 'Spooling', 'Pipelining'],
    correctAnswer: 1,
    explanation: 'Aging gradually boosts the priority of processes that have spent a long duration in the ready queue, guaranteeing eventual execution.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'cpu-scheduling',
  },
  {
    stableId: 'final-exam-q005',
    topic: 'final-exam',
    question: 'What are the three criteria required to solve the Critical Section Problem in process synchronization?',
    options: [
      'Mutual Exclusion, Progress, Bounded Waiting',
      'Hold and Wait, No Preemption, Circular Wait',
      'Compaction, Paging, Segmentation',
      'FCFS, SJF, Round Robin',
    ],
    correctAnswer: 0,
    explanation: 'Any valid critical section synchronization solution must satisfy Mutual Exclusion (only one at a time), Progress (no deadlock on entry), and Bounded Waiting (no starvation).',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'synchronization-race-conditions',
  },
  {
    stableId: 'final-exam-q006',
    topic: 'final-exam',
    question: 'What is an "Atomic Operation" in concurrent systems?',
    options: [
      'An operation that splits across multiple CPU cores',
      'An operation that executes completely without any possibility of interruption or interleaving',
      'An instruction that can only run on quantum computers',
      'An operation requiring disk I/O verification',
    ],
    correctAnswer: 1,
    explanation: 'Atomic instructions (like Test-and-Set or Compare-and-Swap) execute as an indivisible unit, preventing race conditions.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'synchronization-race-conditions',
  },
  {
    stableId: 'final-exam-q007',
    topic: 'final-exam',
    question: 'Which algorithm is utilized by operating systems to test for safe states and avoid deadlocks before granting requested resources?',
    options: ['Peterson’s Algorithm', 'Banker’s Algorithm', 'Dekker’s Algorithm', 'Kruskal’s Algorithm'],
    correctAnswer: 1,
    explanation: 'Dijkstra’s Banker’s Algorithm simulates resource allocation to verify that a safe sequence exists before approving a request.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'deadlocks',
  },
  {
    stableId: 'final-exam-q008',
    topic: 'final-exam',
    question: 'In a resource allocation graph (RAG), what does a directed cycle indicate when every resource type has exactly ONE instance?',
    options: [
      'A Deadlock is guaranteed to exist',
      'The system is guaranteed to be in a safe state',
      'Thrashing is taking place',
      'External fragmentation has occurred',
    ],
    correctAnswer: 0,
    explanation: 'If all resource types have single instances, a cycle in the Resource Allocation Graph is both a necessary and sufficient condition for deadlock.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'deadlocks',
  },
  {
    stableId: 'final-exam-q009',
    topic: 'final-exam',
    question: 'What is the key difference between Internal and External Fragmentation in memory allocation?',
    options: [
      'Internal fragmentation is wasted space inside an allocated partition; External fragmentation is unallocated free memory scattered in small blocks between partitions',
      'Internal fragmentation occurs on disk; External fragmentation occurs in CPU cache',
      'External fragmentation is solved by paging; Internal fragmentation is solved by compaction',
      'Internal fragmentation only occurs in Virtual Machines',
    ],
    correctAnswer: 0,
    explanation: 'Internal fragmentation is unused memory within an assigned block (due to fixed partition sizes). External fragmentation is total free memory broken into unusable small pieces.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'memory-management',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'final-exam-q010',
    topic: 'final-exam',
    question: 'Given 3 page frames and reference string [1, 2, 3, 2, 1, 4], how many page faults occur under Optimal Page Replacement?',
    options: ['3 Page Faults', '4 Page Faults', '5 Page Faults', '6 Page Faults'],
    correctAnswer: 1,
    explanation: '1. Ref 1 -> [1] (Fault 1)\n2. Ref 2 -> [1, 2] (Fault 2)\n3. Ref 3 -> [1, 2, 3] (Fault 3)\n4. Ref 2 -> Hit [1, 2, 3]\n5. Ref 1 -> Hit [1, 2, 3]\n6. Ref 4 -> replaces 3 (since 3 is not referenced again) -> [1, 2, 4] (Fault 4). Total = 4 page faults.',
    difficulty: 'hard',
    marks: 2,
    reviewTopicSlug: 'virtual-memory',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'final-exam-q011',
    topic: 'final-exam',
    question: 'What occurs during a Page Fault trap?',
    options: [
      'The CPU immediately shuts down to protect memory',
      'The OS trap handler pauses the faulting process, fetches the required page from disk swap into a free RAM frame, updates the page table, and resumes the process',
      'The application process is permanently terminated',
      'All caches are erased and the kernel restarts',
    ],
    correctAnswer: 1,
    explanation: 'A page fault signals that the requested virtual page is not resident in physical RAM. The OS fetches it from secondary storage into RAM and updates valid bits.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'virtual-memory',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'final-exam-q012',
    topic: 'final-exam',
    question: 'Which page replacement policy replaces the page that has not been referenced for the longest period of past time?',
    options: ['First-In, First-Out (FIFO)', 'Least Recently Used (LRU)', 'Least Frequently Used (LFU)', 'Most Recently Used (MRU)'],
    correctAnswer: 1,
    explanation: 'LRU (Least Recently Used) evaluates backward in time and evicts the page that has remained untouched the longest.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'virtual-memory',
    labSimulatorLink: '/os-lab/memory-management',
  },
  {
    stableId: 'final-exam-q013',
    topic: 'final-exam',
    question: 'In disk arm scheduling with cylinders 0-199, head at 100 moving toward higher numbers, and requests [120, 30, 180], in what order does SCAN service them?',
    options: [
      '120 -> 180 -> 199 (boundary) -> 30',
      '30 -> 120 -> 180',
      '120 -> 30 -> 180',
      '180 -> 120 -> 30',
    ],
    correctAnswer: 0,
    explanation: 'SCAN moves continuously in the current direction (towards 199), servicing 120, then 180, reaches boundary 199, then reverses direction to service 30.',
    difficulty: 'hard',
    marks: 2,
    reviewTopicSlug: 'disk-management',
    labSimulatorLink: '/os-lab/disk-scheduling',
  },
  {
    stableId: 'final-exam-q014',
    topic: 'final-exam',
    question: 'In C-SCAN (Circular SCAN) disk scheduling, what is the main benefit over standard SCAN?',
    options: [
      'Provides a more uniform and fair waiting time across all cylinders by only servicing requests in one direction',
      'Eliminates all disk seek time completely',
      'Halves the rotational speed of the hard drive',
      'Eliminates the need for disk arm motors',
    ],
    correctAnswer: 0,
    explanation: 'C-SCAN treats cylinders as a circular list, returning directly to cylinder 0 after reaching the end without servicing on the return pass, providing uniform wait times.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'disk-management',
    labSimulatorLink: '/os-lab/disk-scheduling',
  },
  {
    stableId: 'final-exam-q015',
    topic: 'final-exam',
    question: 'What is the purpose of a Journaling File System (such as ext4 or NTFS)?',
    options: [
      'To record intended file system metadata updates in a dedicated journal log before committing them, allowing rapid recovery after a power failure or crash',
      'To print all user files to a physical journal log',
      'To encrypt all user passwords using SHA-512',
      'To increase network download speeds',
    ],
    correctAnswer: 0,
    explanation: 'Journaling writes file operations to a circular log first, preventing metadata corruption and lengthy filesystem checks (`fsck`) after crashes.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'file-systems',
  },
  {
    stableId: 'final-exam-q016',
    topic: 'final-exam',
    question: 'Which of the following describes the function of the Fork-Exec pattern in Unix/Linux?',
    options: [
      '`fork()` duplicates the current process to create a child; `exec()` replaces the child’s memory space with a new executable program',
      '`fork()` terminates a process; `exec()` pauses execution',
      '`fork()` formats the disk; `exec()` boots the kernel',
      '`fork()` creates a thread; `exec()` allocates a page table',
    ],
    correctAnswer: 0,
    explanation: 'The standard process creation pattern in POSIX systems is `fork()` (cloning PCB and address space) followed by `exec()` (loading new binary code).',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'processes',
  },
  {
    stableId: 'final-exam-q017',
    topic: 'final-exam',
    question: 'What is the difference between a Hard Link and a Symbolic (Soft) Link in file systems?',
    options: [
      'A Hard Link points directly to the file’s Inode number; a Symbolic Link is a special file containing the path string to another file',
      'A Hard Link only works across different hard drives; a Soft Link works on one drive',
      'A Hard Link is deleted when the original file is renamed; a Soft Link remains valid',
      'There is no functional difference',
    ],
    correctAnswer: 0,
    explanation: 'Hard links increment the inode link count and point to the exact same inode. Symbolic links are pointer files holding path targets.',
    difficulty: 'medium',
    marks: 1,
    reviewTopicSlug: 'file-systems',
  },
  {
    stableId: 'final-exam-q018',
    topic: 'final-exam',
    question: 'What hardware protection mechanism ensures an errant user program cannot write into another process\'s memory or the OS kernel?',
    options: [
      'Base and Limit Registers / Memory Management Unit (MMU) Page Table Protection Bits',
      'High-speed network firewalls',
      'Dynamic Link Libraries (DLL)',
      'Disk Seek Arm Encoders',
    ],
    correctAnswer: 0,
    explanation: 'Base and limit registers (or MMU page table permission bits: Read/Write/Execute/User/Supervisor) trap unauthorized out-of-bounds memory accesses.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'user-vs-kernel-mode',
  },
  {
    stableId: 'final-exam-q019',
    topic: 'final-exam',
    question: 'In OS virtualization, what is "Type 1 Bare-Metal" hypervisor (e.g. VMware ESXi, KVM)?',
    options: [
      'Hypervisor software running directly on bare physical hardware without an underlying host operating system',
      'Software running on Windows 11 as an app',
      'A browser extension that runs JavaScript',
      'A physical graphics card firmware driver',
    ],
    correctAnswer: 0,
    explanation: 'Type 1 hypervisors have direct hardware access, providing high performance and isolation for enterprise cloud data centers.',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'virtualization-containers',
  },
  {
    stableId: 'final-exam-q020',
    topic: 'final-exam',
    question: 'What score is required on this Certification Examination to achieve the prestigious "OS Master" Certification Badge?',
    options: [
      '50%',
      '60%',
      '80% or higher',
      '100% with zero mistakes only',
    ],
    correctAnswer: 2,
    explanation: 'Achieving an 80% or higher score (16+ out of 20) demonstrates comprehensive mastery across all OS domains and unlocks the OS Master badge!',
    difficulty: 'easy',
    marks: 1,
    reviewTopicSlug: 'intro-to-os',
  },
];

export const seedQuizzes = async (): Promise<{ inserted: number; updated: number }> => {
  const operations = seedQuestions.map(q => ({
    updateOne: {
      filter: { stableId: q.stableId },
      update: { $set: q },
      upsert: true,
    },
  }));

  const result = await Question.bulkWrite(operations);
  const inserted = result.upsertedCount || 0;
  const updated = result.modifiedCount || 0;

  return { inserted, updated };
};
